name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build atomci backend
        run: make build
      - name: Build frontend page
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          cd web
          yarn install
          yarn run build
      
  image:
    if: github.repository == 'go-atomci/atomci' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: github.event_name != 'pull_request'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: github.event_name != 'pull_request'
      
      -
        name: Build and push atomci frontend
        uses: docker/build-push-action@v2
        with:
          context: ./web
          pull: true
          push: true
          #build-args: |
          #    arg1=value1
          #    arg2=value2
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/atomci-frontend:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/atomci-frontend:latest
        if: github.event_name != 'pull_request'
      
      -
        name: Build and push atomci backend 
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          #build-args: |
          #    arg1=value1
          #    arg2=value2
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/atomci:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/atomci:latest
        if: github.event_name != 'pull_request'
